#!/bin/bash
# File: 201-systemd-network-dnssec-disable.sh
# Title: Disable the systemd-network from handling of DNSSEC resolver
# Description:
#
# There are two ways to disable DNSSEC handling by systemd:
#
#   1. At system-wide level, by systemd-resolved get
#      drops in the:
#      /etc/systemd/resolved.conf.d/dnssec-disable.conf
#
#        [Resolved]
#        DNSSEC=false
#
#   2. At per-link basis, by systemd-networkd, if and
#      only if networkd unit is running get sets in
#      the /etc/systemd/network/xxxx.network file
#
#
# As of systemd v238, LLMNR defaults to on if not mentioned
#
# Reference:
#
# * https://wiki.archlinux.org/title/Systemd-resolved
echo "Disable DNSSEC handling by systemd"
echo
BUILDROOT="${BUILDROOT:-build}"

if [ "${BUILDROOT:0:1}" == '/' ]; then
  if [ $UID -ne 0 ]; then
    echo "Non-root detected; may prompt for SUDO password(s)."
    read -rp "Press ENTER to continue; or Ctrl-C to quit."
    SUDO_BIN="/usr/bin/sudo"
  fi
else
  mkdir "$BUILDROOT"
fi

source ../easy-admin-installer.sh
source ../distro-os.sh
FILE_SETTING_PERFORM='yes'

flex_ckdir "/etc"
flex_ckdir "/etc/systemd"

FILE_SETTINGS_FILESPEC="${BUILDROOT}/file-systemd-resolved-dnssec-fallback-disabled.sh"

dropin_filename="dnssec-fallback-disabled.conf"
dropin_dirspec="/etc/systemd/resolved.conf.d"
dropin_filespec="${dropin_dirspec}/$dropin_filename"

flex_mkdir "$dropin_dirspec"


echo "Creating $dropin_filespec ..."
cat << DROPIN_EOF | $SUDO_BIN tee "${BUILDROOT}${CHROOT_DIR}/$dropin_filespec" > /dev/null
#
# File: ${dropin_filename}
# Path: ${dropin_dirspec}
# Title: Disable DNSSEC in systemd-resolved
# Generated by: $(basename "$0")
# Created on: $(date)
# Description:
#
#   If systemd-resolved does not receive DNS server
#   addresses from the network manager and no DNS
#   servers are configured manually then
#   systemd-resolved falls back to the fallback DNS
#   addresses to ensure that DNS resolution always
#   works.
#
# Note: The fallback DNS are in this order: Cloudflare,
#       Quad9 (without filtering and without DNSSEC)
#       and Google; see the systemd PKGBUILD where
#       the servers are defined.
#
#   The addresses can be changed by setting
#   FallbackDNS= in resolved.conf(5).
#
#     File:/etc/systemd/resolved.conf.d/fallback_dns.conf
#       [Resolve]
#       FallbackDNS=127.0.0.1 ::1
#
#   To disable the fallback DNS functionality set the
#   FallbackDNS option without specifying any addresses:
#
#     File:/etc/systemd/resolved.conf.d/fallback_dns.conf
#       [Resolve]
#       FallbackDNS=
#
# Note: Systemd's primary job is just to start up
#       things, not to manage DNS querying;
#       we leave that to ISC Bind9
#
[Resolve]
FallbackDNS=

DROPIN_EOF
flex_chown "root:root" "$dropin_dirspec"
flex_chmod 0644 "$dropin_dirspec"  # really should be 0640
echo

echo "Done."
