#!/bin/bash
# File: 201-systemd-network-dnssec-disable.sh
# Title: Disable the Fallback mechansim by systemd DNS resolver
# Description:
#   There are two ways to disable Fallback DNS handling by systemd:
#
#   1. At system-wide level, by systemd-resolved get
#      drops in the
#      /etc/systemd/resolved.conf file or the
#      /etc/systemd/resolved.conf.d/dnssec-fallback-disable.conf
#      file.
#
#        [Resolved]
#        FallbackDNS=false
#
#   2. At per-link basis, by systemd-networkd, if and
#      only if networkd unit is running get sets in
#      the /etc/systemd/network/network.conf or
#      the /etc/systemd/network/xxxx.network file.
#
#
#   As of systemd v238, LLMNR defaults to on if not mentioned
#
# Privilege required: root
# OS: Debian
# Kernel: Linux
#
# Files impacted:
#  read   - /etc/systemd/resolved.conf.d/#dns-fallback-disabled.conf
#  create - /etc/systemd/resolved.conf.d/
#         - /etc/systemd/resolved.conf.d/#dns-fallback-disabled.conf
#  modify - none
#  delete - none
#
# Note:
#   This is a bizarre use of Microsoft DotNet for GUI-less hosts.
#   Made NOT an executable due to lack of security review
#
# Environment Variables:
#   BUILDROOT - set to '/' to actually install directly into your filesystem
#
# Prerequisites (package name):
#   awk (mawk)
#   basename (coreutils)
#   cat (coreutils)
#   date (coreutils)
#   grep (grep)
#   mkdir (coreutils)
#   tail (coreutils)
#   tee (coreutils)
#
# Reference:
# - https://wiki.archlinux.org/title/Systemd-resolved
#

echo "Disable Fallback DNS handling by systemd"
echo
BUILDROOT="${BUILDROOT:-build}"

find_keyword() {
  (( found_keyword=0 ))
  local filespec=$1
  local keyword=$2
  found_keyword=$(grep -e -c "^\s*${keyword}\s*=" /dev/null "$filespec")
  if [ "$found_keyword" -ge 1 ]; then
    return 1
  else
    return 0
  fi
}

# systemd conf files only uses last-encountered
# keyword and its value in the case of multiple
# declaration of its same keyword.
find_keyvalue() {
  result=''
  local filespec=$1
  local keyword=$2
  # Find last matching line
  result="$(grep -e "^\s*${keyword}\s*=" /dev/null "$filespec" |
    tail -n 1 |
    awk -F= '{print $2}')"
}

if [ "${BUILDROOT:0:1}" == '/' ]; then
  if [ $UID -ne 0 ]; then
    echo "Non-root detected; may prompt for SUDO password(s)."
    read -rp "Press ENTER to continue; or Ctrl-C to quit."
    SUDO_BIN="/usr/bin/sudo"
  fi
else
  mkdir -p "./$BUILDROOT"
  mkdir -p "./${BUILDROOT}/etc"
  mkdir -p "./${BUILDROOT}/etc/systemd"
fi

source ../easy-admin-installer.sh
source ../distro-os.sh
FILE_SETTING_PERFORM='yes'
FILE_SETTINGS_FILESPEC="${BUILDROOT}/file-systemd-resolved-dns-fallback-disabled.sh"

resolv_filename="resolved.conf"
resolv_dirspec="/etc/systemd"
resolv_filespec="${resolv_dirspec}/$resolv_filename"

find_keyvalue "$resolv_filespec" 'FallbackDNS'
# result to find_keyvalue is in result

dropin_filename="dns-fallback-disabled.conf"
dropin_dirspec="/etc/systemd/resolved.conf.d"
dropin_filespec="${dropin_dirspec}/$dropin_filename"

COMMENT_OUT=
if [ -n "$result" ]; then
  echo "*****************************************************************"
  echo "WARNING: There is a FallbackDNS= statement in $resolv_filespec"
  echo "         You need to comment that out or delete that line."
  echo "         before using this dropin $dropin_filespec file."
  echo "*****************************************************************"
  COMMENT_OUT="WARNING: Need to comment out $(grep -n -e '^\s*FallbackDNS\s*=' "$dropin_filespec" | tail -n1)\n# in file $dropin_filespec"
fi

flex_ckdir "/etc"
flex_ckdir "/etc/systemd"
flex_ckdir "$dropin_dirspec"

BIN_BASENAME="$(basename "$0")"
DATE_TXT="$(date)"
echo "Creating ${BUILDROOT}${CHROOT_DIR}/$dropin_filespec ..."
cat <<DROPIN_EOF | $SUDO_BIN tee "${BUILDROOT}${CHROOT_DIR}/$dropin_filespec" >/dev/null
#
# File: ${dropin_filename}
# Path: ${dropin_dirspec}
# Title: Disable Fallback DNS in systemd-resolved
# Generated by: ${BIN_BASENAME}
# Created on: ${DATE_TXT}
# Description:
#
#   If systemd-resolved does not receive DNS server
#   addresses from the network manager and no DNS
#   servers are configured manually then
#   systemd-resolved falls back to the fallback DNS
#   addresses to ensure that DNS resolution always
#   works.
#
# Note: The fallback DNS are in this order: Cloudflare,
#       Quad9 (without filtering and without DNSSEC)
#       and Google; see the systemd PKGBUILD where
#       the servers are defined.
#
#   The addresses can be changed by setting
#   FallbackDNS= in resolved.conf(5).
#
#     File:/etc/systemd/resolved.conf.d/fallback_dns.conf
#       [Resolve]
#       FallbackDNS=127.0.0.1 ::1
#
#   To disable the fallback DNS functionality set the
#   FallbackDNS option without specifying any addresses:
#
#     File:/etc/systemd/resolved.conf.d/fallback_dns.conf
#       [Resolve]
#       FallbackDNS=
#
# Note: Systemd's primary job is just to start up
#       things, not to manage DNS querying;
#       we leave that DNS querying to ISC Bind9
#       as a form of greatly lowering attack surface
#
# ${COMMENT_OUT}
#
[Resolve]
FallbackDNS=

DROPIN_EOF

flex_chown "root:root" "$dropin_dirspec"
flex_chmod 0644 "$dropin_dirspec" # really should be 0640
echo

echo "Done."
