#!/bin/sh
# init
# descrption: invoked early in “shorewall start” and “shorewall restart”

# State: run-time
# Action: Done at shorewall 'load, refresh, reload, restart restore, start'
# Allowable pragma: '?INCLUDE' statement

/etc/shorewall/update_tor_ipsets.sh
/etc/shorewall/timeframe-mac-unblocked.sh

